set_property SRC_FILE_INFO {cfile:/home/y/fpga/project_1/project_1.srcs/constrs_1/new/project.xdc rfile:../../../project_1.srcs/constrs_1/new/project.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/zynq_ultra_ps_e_0/inst/pl_clk0]]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/signal_controller_0_ADDRB[0]} {design_1_i/signal_controller_0_ADDRB[1]} {design_1_i/signal_controller_0_ADDRB[2]} {design_1_i/signal_controller_0_ADDRB[3]} {design_1_i/signal_controller_0_ADDRB[4]} {design_1_i/signal_controller_0_ADDRB[5]} {design_1_i/signal_controller_0_ADDRB[6]} {design_1_i/signal_controller_0_ADDRB[7]} {design_1_i/signal_controller_0_ADDRB[8]} {design_1_i/signal_controller_0_ADDRB[9]} {design_1_i/signal_controller_0_ADDRB[10]} {design_1_i/signal_controller_0_ADDRB[11]} {design_1_i/signal_controller_0_ADDRB[12]} {design_1_i/signal_controller_0_ADDRB[13]} {design_1_i/signal_controller_0_ADDRB[14]} {design_1_i/signal_controller_0_ADDRB[15]} {design_1_i/signal_controller_0_ADDRB[16]} {design_1_i/signal_controller_0_ADDRB[17]} {design_1_i/signal_controller_0_ADDRB[18]} {design_1_i/signal_controller_0_ADDRB[19]} {design_1_i/signal_controller_0_ADDRB[20]} {design_1_i/signal_controller_0_ADDRB[21]} {design_1_i/signal_controller_0_ADDRB[22]} {design_1_i/signal_controller_0_ADDRB[23]} {design_1_i/signal_controller_0_ADDRB[24]} {design_1_i/signal_controller_0_ADDRB[25]} {design_1_i/signal_controller_0_ADDRB[26]} {design_1_i/signal_controller_0_ADDRB[27]} {design_1_i/signal_controller_0_ADDRB[28]} {design_1_i/signal_controller_0_ADDRB[29]} {design_1_i/signal_controller_0_ADDRB[30]} {design_1_i/signal_controller_0_ADDRB[31]}]]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/signal_controller_0_WEB[0]} {design_1_i/signal_controller_0_WEB[1]} {design_1_i/signal_controller_0_WEB[2]} {design_1_i/signal_controller_0_WEB[3]}]]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/signal_controller_0_DINB[0]} {design_1_i/signal_controller_0_DINB[1]} {design_1_i/signal_controller_0_DINB[2]} {design_1_i/signal_controller_0_DINB[3]} {design_1_i/signal_controller_0_DINB[4]} {design_1_i/signal_controller_0_DINB[5]} {design_1_i/signal_controller_0_DINB[6]} {design_1_i/signal_controller_0_DINB[7]} {design_1_i/signal_controller_0_DINB[8]} {design_1_i/signal_controller_0_DINB[9]} {design_1_i/signal_controller_0_DINB[10]} {design_1_i/signal_controller_0_DINB[11]} {design_1_i/signal_controller_0_DINB[12]} {design_1_i/signal_controller_0_DINB[13]} {design_1_i/signal_controller_0_DINB[14]} {design_1_i/signal_controller_0_DINB[15]} {design_1_i/signal_controller_0_DINB[16]} {design_1_i/signal_controller_0_DINB[17]} {design_1_i/signal_controller_0_DINB[18]} {design_1_i/signal_controller_0_DINB[19]} {design_1_i/signal_controller_0_DINB[20]} {design_1_i/signal_controller_0_DINB[21]} {design_1_i/signal_controller_0_DINB[22]} {design_1_i/signal_controller_0_DINB[23]} {design_1_i/signal_controller_0_DINB[24]} {design_1_i/signal_controller_0_DINB[25]} {design_1_i/signal_controller_0_DINB[26]} {design_1_i/signal_controller_0_DINB[27]} {design_1_i/signal_controller_0_DINB[28]} {design_1_i/signal_controller_0_DINB[29]} {design_1_i/signal_controller_0_DINB[30]} {design_1_i/signal_controller_0_DINB[31]}]]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/blk_mem_gen_0_doutb[0]} {design_1_i/blk_mem_gen_0_doutb[1]} {design_1_i/blk_mem_gen_0_doutb[2]} {design_1_i/blk_mem_gen_0_doutb[3]} {design_1_i/blk_mem_gen_0_doutb[4]} {design_1_i/blk_mem_gen_0_doutb[5]} {design_1_i/blk_mem_gen_0_doutb[6]} {design_1_i/blk_mem_gen_0_doutb[7]} {design_1_i/blk_mem_gen_0_doutb[8]} {design_1_i/blk_mem_gen_0_doutb[9]} {design_1_i/blk_mem_gen_0_doutb[10]} {design_1_i/blk_mem_gen_0_doutb[11]} {design_1_i/blk_mem_gen_0_doutb[12]} {design_1_i/blk_mem_gen_0_doutb[13]} {design_1_i/blk_mem_gen_0_doutb[14]} {design_1_i/blk_mem_gen_0_doutb[15]} {design_1_i/blk_mem_gen_0_doutb[16]} {design_1_i/blk_mem_gen_0_doutb[17]} {design_1_i/blk_mem_gen_0_doutb[18]} {design_1_i/blk_mem_gen_0_doutb[19]} {design_1_i/blk_mem_gen_0_doutb[20]} {design_1_i/blk_mem_gen_0_doutb[21]} {design_1_i/blk_mem_gen_0_doutb[22]} {design_1_i/blk_mem_gen_0_doutb[23]} {design_1_i/blk_mem_gen_0_doutb[24]} {design_1_i/blk_mem_gen_0_doutb[25]} {design_1_i/blk_mem_gen_0_doutb[26]} {design_1_i/blk_mem_gen_0_doutb[27]} {design_1_i/blk_mem_gen_0_doutb[28]} {design_1_i/blk_mem_gen_0_doutb[29]} {design_1_i/blk_mem_gen_0_doutb[30]} {design_1_i/blk_mem_gen_0_doutb[31]}]]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/signal_controller_0_CLKB]]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/signal_controller_0_ENB]]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/signal_controller_0_RSTB]]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_pl_clk0]
